# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: recipe # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  create:
    handler: recipe/create.create
    events:
      - http:
          path: recipe
          method: post
          cors: true

  list:
    handler: recipe/list.list
    events:
      - http:
          path: recipe
          method: get
          cors: true

  get:
    handler: recipe/get.get
    events:
      - http:
          path: recipe/{id}
          method: get
          cors: true

  update:
    handler: recipe/update.update
    events:
      - http:
          path: recipe/{id}
          method: put
          cors: true

  delete:
    handler: recipe/delete.delete
    events:
      - http:
          path: recipe/{id}
          method: delete
          cors: true

resources:
  Resources:
    RecipesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
TableName: 'recipes'

